### ISSUE TITLE
unoconv: Cannot find a suitable office installation on your system MAC

### ISSUE THREAD

**Issue by edoardo849** [dagwieers/unoconv#163]
I've downloaded Unoconv on my mac and I've tried it all: ./unoconv, python unoconv but it continues to say that 

    unoconv: Cannot find a suitable office installation on your system

but my openoffice is in Applications/OpenOffice

**Comment by vittala** [comment]
Might be down to OpenOffice on Mac now installing under /Applications/OpenOffice.app/ rather than /Applications/OpenOffice.org.app/. The following patch makes it work for me with OpenOffice 4.1.1:

<pre>
--- unoconv.orig	2015-04-01 15:07:25.000000000 +0100
+++ unoconv	2015-04-01 15:07:44.000000000 +0100
@@ -90,6 +90,7 @@
         elif os.name in ( 'mac', ) or sys.platform in ( 'darwin', ):
             extrapaths += [ '/Applications/LibreOffice.app/Contents',
                             '/Applications/NeoOffice.app/Contents',
+                            '/Applications/OpenOffice.app/Contents',
                             '/Applications/OpenOffice.org.app/Contents' ]
 
         else:
</pre>

**Comment by skywinder** [comment]
@vittala can you share your patch as a branch or  a separate file?

**Comment by vittala** [comment]
@skywinder - I've created a pull request: https://github.com/dagwieers/unoconv/pull/250

**Comment by dagwieers** [comment]
I think we can close this support ticket. Thanks everyone :+1:

**Comment by dagwieers** [comment]
Since this change is now pulled, I think we can close this support ticket.

Thanks everyone ! :+1:

**Comment by skywinder** [comment]
Use `brew install unoconv --HEAD` until the new version is not released
(I'm waiting approve of @dagwieers to release new version)

**Comment by EvgeniyGorbachev** [comment]
A good instruction for installation: https://docs.moodle.org/35/en/Universal_Office_Converter_(unoconv)#Installing_unoconv_on_OS_X
