### ISSUE TITLE
unoconv cannot find OpenOffice 4.0.0 installation path

### ISSUE THREAD

**Issue by gabrielopritoiu** [dagwieers/unoconv#165]
Hi all,

When I try to convert .odt file to pdf using OpenOffice 4.0.0 I get the following error message:

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

OpenOffice is installed at the following path: "C:\Program Files (x86)\OpenOffice 4"

Also tried with OpenOffice 3.4.1 and it worked fine.

**Comment by dagwieers** [comment]
You did not specify the exact commandline you are using, and I hate to make assumptions.

Can you look at the [Troubleshooting instructions](https://github.com/dagwieers/unoconv#troubleshooting-instructions), follow them and report back ?

**Comment by bjdmeest** [comment]
I had the same problem with OpenOffice 4 using following commandline, I think because OpenOffice changed their install paths from OpenOffice.org to OpenOffice 4. Removing the .org in lines https://github.com/dagwieers/unoconv/blob/46a084294291bd42ae01364ae1ab7932487bd053/unoconv#L83 and https://github.com/dagwieers/unoconv/blob/46a084294291bd42ae01364ae1ab7932487bd053/unoconv#L87 did the trick for me

```
 unoconv -o output.html -f html input.docx
```

**Comment by castmetal** [comment]
Hi, I resolve with Unotools. I hope that you helps others: https://pypi.python.org/pypi/unotools
