### ISSUE TITLE
Handling exit code 81

### ISSUE THREAD

**Issue by dvandersluis** [dagwieers/unoconv#192]
If user installation files do not already exist, the first time LibreOffice starts it will create the files and then immediately quit with exit code 81 (I'm not sure about OpenOffice, but I assume it works similarly). In this case, unoconv will fail, because the listener will not remain open long enough to be used. This behaviour will happen repeatedly if the `env:UserInstallation` variable is set when launching soffice.

I have tested out this scenario in two environments (Mac OSX 10.9 and Ubuntu 12.04). On the mac, unoconv will launch the executable `soffice`, whereas on Ubuntu, it launches `soffice.bin` (this file is not present on MacOSX, at least not with LO 4.2). As far as I can tell, the difference between `soffice` and `soffice.bin` is that `soffice` is a wrapper around `soffice.bin` (where available), and includes logic to automatically restart the executable when an exit code 81 is encountered. Therefore, on MacOSX, I do not run into the problem of unoconv failing because of exit code 81, but on ubuntu I do.

As mentioned, `soffice` (no `.bin`) is present on Ubuntu as well (again, at least for LO 4.2), and using that executable instead of `soffice.bin` seems to have no adverse effects. Does anyone know why the choice was made to use `soffice.bin` instead?

**Comment by dagwieers** [comment]
Thanks for this. It was an issue which was open for a long time.

I merged your patch with the master branch and committed it with you as the author, see e4f65ed0d23c21e98ef55cbc69b74119bab26b44. I hope you didn't mind. Let's go and close some of the same issues in the tracker :) Thanks again !

**Comment by dagwieers** [comment]
@dvandersluis AFAIR using `soffice` instead of `soffice.bin` on older releases worked more reliably (in some cases soffice appeared not to be properly shut down). It is possible we fixed that problem in unoconv (or upstream) in the meantime and there is no longer a need for it anymore. However, I prefer to handle soffice directly and not depend too much on logic that I cannot control. So I do have a preference to using soffice.bin over soffice (even when we managed to fix all issues). So I am really glad we implement a fix for the Error 81 issue :-)
