### ISSUE TITLE
Unoconv is not able to identify the OpenOffice installation in MacOS X.

### ISSUE THREAD

**Issue by shilpi230** [dagwieers/unoconv#252]
Earlier i was using Libreoffice with unoconv. But due to some problem in Libreoffice I shifted to open office. But unoconv command is not working as it is not able to find the open office installation in the system. 

Error: `unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues`

**Comment by jirib** [comment]
Check paths in https://github.com/dagwieers/unoconv/blob/master/unoconv
Is your path there?

**Comment by BeatsMe** [comment]
I had the same problem with LibreOffice v4.4.2. But after downgrading to v4.3.6, the problem has gone. 
The file structure under /Applications/LibreOffice.app/Contents/MacOS between 4.4.2 and 4.3.6 are very different. Need modification on the source, I think.

**Comment by shilpi230** [comment]
No my path is this `/Applications/OpenOffice.app/Contents/MacOS`

**Comment by lourinaldi** [comment]
Same issue, my path is /opt/homebrew-cask/Caskroom/libreoffice/

**Comment by BeatsMe** [comment]
I think if you leave the path /opt/homebrew-cask/Caskroom/libreoffice/ as
it is, you have to specify
UNO_PATH=/opt/homebrew-cask/Caskroom/libreoffice.app/Contents . Or `brew
linkapps libreoffice.`

If neither works, I recommend downgrading libreoffice.

After downgrading to LibreOffice 4.3.6, my unoconv has worked.

I think the problem has been caused because of the file structure
difference between 4.3.6 and 4.4.2 of LibreOffice, which is quite different

.

2015-04-15 23:15 GMT+09:00 Lou Rinaldi <notifications@github.com>:

> Same issue, my path is /opt/homebrew-cask/Caskroom/libreoffice/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dagwieers/unoconv/issues/252#issuecomment-93419593>.
>



-- 
森口 晃宏
ameniutaeba1978@gmail.com

**Comment by skywinder** [comment]
Dup of #163 fixed in #250

**Comment by skywinder** [comment]
Use `brew install unoconv --HEAD` until the new version is not released
