### ISSUE TITLE
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice

### ISSUE THREAD

**Issue by jhrs21** [dagwieers/unoconv#372]
Hello, I have Ubuntu 14.04 and I am having some problems with this library. 

`unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice`
`ERROR: No module named unohelper`

`unoconv: Cannot find a suitable office installation on your system.`
`ERROR: Please locate your office installation and send your feedback to:`
       `http://github.com/dagwieers/unoconv/issue`

At first I had problems with uno library, but I google it a lot and installing uno through `easy_install` was possible to remove the problem with uno, but now I have this one with unohelper.

I know that  #49 talks about this problem, but the solution in there is to change and use python3, I can't do this, I need to mantain _python 2.7.6_

Thanks,

**Comment by JoeLucky** [comment]
@jhrs21 Linux installs uno/unohelper itself. Probably beacuse you install several version of Python, try to find uno.py/unohelper.py in your system and copy to your current python site-packages path.

**Comment by stas00** [comment]
The workaround/fix is [here](https://github.com/dagwieers/unoconv/issues/49#issuecomment-416317222).

**Comment by regebro** [comment]
I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:

```
UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....
```
Yes, that's fairly annoying, but only happens with multiple LibreOffice and/or Python installations.

Further discussion on #49

**Comment by jdhao** [comment]
@regebro I am using libreoffice 6.0.7.3. Libreoffice is installed on `/usr/lib/libreoffice`. There is no python under `/usr/lib/libreoffice/program`.

**Comment by shria-devarakonda** [comment]
@jdhao late reply but i was stuck on this for hours cuz i'm a newbie, so if your'e on Ubuntu, the steps which worked for me are (assuming you've installed unoconv): 
Navigate to /usr/bin and type"sudo vi unoconv"
Edit the first line, change it to: "!/usr/bin/python3"
after that, run the below command:
`UNOPATH=/usr/lib/libreoffice /usr/bin/unoconv -vvv -f pdf name_of_file.docx`

**Comment by jdhao** [comment]
> @jdhao late reply but i was stuck on this for hours cuz i'm a newbie, so if your'e on Ubuntu, the steps which worked for me are (assuming you've installed unoconv): 
> Navigate to /usr/bin and type"sudo vi unoconv"
> Edit the first line, change it to: "!/usr/bin/python3"
> after that, run the below command:
> `UNOPATH=/usr/lib/libreoffice /usr/bin/unoconv -vvv -f pdf name_of_file.docx`
> 

thanks, actually I have solved it and logged it here: https://jdhao.github.io/2020/03/30/pptx_to_image/#use-unoconv.

The solution is the same. cheers😉

**Comment by maik-s** [comment]
# Some of the solutions in this thread are not sustainable and can break with system updates

By directly modifying the files `/usr/bin/unoconv`  file you risk that a potential system update will **overwrite** these files and your dependency crashes again.

The described issue of `unoconv` being unable to find `pyuno`  is probably because the both mentioned files cannot be found since your `unoconv` is called from within a separated python environment as `virtualenv` does.

Therefore, I suggest fixing the problem by doing the following:

1. Understand in which environment your application runs and note this `virtuelenv` path (e.g. `/path/to/your/virtualenv/`).
2. Find the directory where the system installed `uno.py` and `unohelper.py` by running `find / -type f -name "unohelper.py" 2>/dev/null` . In my case it is `/usr/lib/python3/dist-packages/`
3. Create two symlinks to these files within your virtualenv path by executing:

```
ln -s /usr/lib/python3/dist-packages/uno.py /path/to/your/virtualenv/lib/python3.8/site-packages/uno.py
ln -s /usr/lib/python3/dist-packages/unohelper.py /path/to/your/virtualenv/lib/python3.8/site-packages/unohelper.py
```
**Note:** Set the correct values for your paths, as your python version might be different.
