### ISSUE TITLE
MathType equations in docx file generates very small images

### ISSUE THREAD

**Issue by chinakr** [dagwieers/unoconv#91]
All MathType equations in docx file generates very small images with unoconv convertion. 

Generally, the generated equation images are hard to regonize. For example, the equation 1/10 will be 12 x 23 pixles and 3^2 will be 10 x12 pixels. The equation images are in GIF format. 

How can I deal with these situations? Is there an argument that can scale the equation images? Thanks a lot!

**Comment by dagwieers** [comment]
I don't know what to do with this issue.
Is it possible to retest the latest unoconv from the master branch and the latest LibreOffice and see if this problem is stil pertinent ? And if it is, feel free to reopen this issue with more information on how we can reproduce the issue.

Thanks for the feedback !
